### PR TITLE
modified the user interface styling for showing the candidates

### PR DESCRIPTION
**Pull request by MahdiRahbar**
Changed the styling of suggested candidates. As a feature, one can add some CSS animation to the way the suggestions show up or fade in. Since this is unnecessary, we can do it in the future.

### CODE REVIEW

**Review by Annoyed-Raven — APPROVED** [review]
Size adjustments look good
Change with the highlight is also good
The popup change, is much better then the devious implementation.

**Comment by MahdiRahbar** [comment]
@Annoyed-Raven Thanks for the review. If you got any error or had any problem please report it.

**Review by nicoprudencio — COMMENTED** [review]
I agree with you guys. We can implement animations by the end and I think now the font sizes adjust better to the screen space. Now we can see a list of suggestions in the popup right?

**Comment by MahdiRahbar** [comment]
@nicoprudencio Yes. This is one of the things that we were supposed to implement.

**Pull request merged**
